# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/a2c.yml
#            https://stable-baselines3.readthedocs.io/en/master/modules/a2c.html
seed: 42

n_timesteps: !!float 1e6
policy: 'MlpPolicy'
n_steps: 16
gae_lambda: 0.95
gamma: 0.99
ent_coef: 0.01
learning_rate: !!float 3e-4
policy_kwargs: "dict(
                  activation_fn=nn.ELU,
                  net_arch=[256, 256],
                  squash_output=False,
                )"
vf_coef: 1.0
max_grad_norm: 1.0
device: "cuda:0"
